from __future__ import annotations
from typing import Protocol


class FetchStrategy(Protocol):
    def rewrite_url(self, url: str) -> str: ...
    def tools(self) -> list[str]: ...
    def retries(self, tier: int) -> int: ...
